version: 0.2.0.{build}
branches:
  only:
  - master
  - appveyor
image: Visual Studio 2022
configuration: Release
platform: x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish H2AIndex -p:PublishProfile=FolderProfile
artifacts:
- path: H2AIndex\bin\publish\win-x64
  name: build